### ISSUE TITLE
Type error causes crash after using create-react-app

### ISSUE THREAD

**Issue by jrmclaren** [ueno-llc/create-ueno-app#10]
Hey team, 

Thanks for making such an awesome product! 

I've got what I hope is a simple one for you. After running `create-ueno-app cra my-app`
the build completes, but quickly crashes displaying the error: 

```
Type error: Duplicate identifier 'LibraryManagedAttributes'.
```
The error appears to originate from within the React @types file. 

I updated some version numbers in my `package.json`, deleted the lock file and
install the dependencies again which seems to have fixed the issue. Here are the updates 
I made to my `package.json` file: 

```
--- a/react-baked-image-test/package.json
+++ b/react-baked-image-test/package.json
@@ -4,8 +4,8 @@
   "private": true,
   "dependencies": {
     "@ueno/react-scripts": "1.1.20",
-    "react": "16.8.4",
-    "react-dom": "16.8.4",
+    "react": "16.10.1",
+    "react-dom": "16.10.1",
     "react-helmet": "5.2.0",
     "react-router-dom": "4.3.1",
     "gsap": "2.1.2",
@@ -15,8 +15,8 @@
   },
   "devDependencies": {
     "@types/node": "11.11.3",
-    "@types/react": "16.8.8",
-    "@types/react-dom": "16.8.2",
+    "@types/react": "16.10.1",
+    "@types/react-dom": "16.10.1",
     "@types/react-helmet": "5.0.8",
     "@types/react-router-dom": "4.3.1",
     "@ueno/stylelint-config": "1.1.2",
@@ -26,6 +26,9 @@
     "tslint-react": "3.6.0",
     "typescript": "3.3.3333"
   },
+  "resolutions": {
+    "@types/react": "16.8.8"
+  },
   "scripts": {
     "dev": "react-scripts start",
     "start": "react-scripts start",
```
Thanks team! Please let me know if there is anything I can do to help you further.
Happy bug squashing!

**Comment by jeremybarbet** [comment]
It has been fixed in latest version of `ueno-cra-starter`
