### ISSUE TITLE
More sample

### ISSUE THREAD

**Issue by mverissimo** [ueno-llc/create-ueno-app#6]
Maybe Can you create a sample with gsap animation, page transition and using gsap devtools

**Comment by jeremybarbet** [comment]
Hey!

That's on our list, especially the page transition that can be interesting to have a base to work with.

Besides, we do have example of gsap animations with the uses of gsap-tools here: https://ueno-llc.github.io/gsap-tools, the website uses the tool itself and there is an example section with couple of links.

**Comment by jeremybarbet** [comment]
I will close this issue. We rather want to keep it simple for the template pages. You can check out the link above to see gsap animations examples.
