### ISSUE TITLE
Issue on npm run prepare 

### ISSUE THREAD

**Issue by cesarchavezcal** [ueno-llc/create-ueno-app#7]
Error: Command failed: npm run prepare 
-f was unexpected at this time

`npm ERR! react-native-starter@2.1.0 prepare: 'patch-package && if [ -f ./scripts/postinstall.sh ]; then sh ./scripts/postinstall.sh; fi'`

**Comment by birkir** [comment]
Windows?

**Comment by cesarchavezcal** [comment]
Yes, windows 10

**Comment by birkir** [comment]
Ok, the starter is assuming Mac OS X for now to enable cross platform development support.

I'll figure something out here, but you won't be able to develop for iOS.

**Comment by cesarchavezcal** [comment]
Ok, thanks. I'm gonna try to run on Mac OS X.

**Comment by jeremybarbet** [comment]
Let's keep this issue open, for windows users to know about that

**Comment by jeremybarbet** [comment]
Work on this issue can be followed here: https://github.com/ueno-llc/react-native-starter/issues/222 I'll close this one to avoid duplicate.
